CustomerSite/Models/ErrorViewModel.cs
using System;

namespace CustomerSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CustomerSite/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace CustomerSite.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult SignIn()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, "oidc");
        }

        public new IActionResult SignOut()
        {
            return SignOut(new AuthenticationProperties { RedirectUri = "/" }, "Cookies", "oidc");
        }

        [Authorize]
        public ActionResult MyProfile()
        {
            return View();
        }
    }
}

CustomerSite/Controllers/CartController.cs
using CustomerSite.SerVices;
using Microsoft.AspNetCore.Mvc;
using ShareModel;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CustomerSite.Controllers
{
    public class CartController : Controller
    {
        [Route("/cart")]
        public IActionResult Index()
        {
            var result = HttpContext.Session.Get<List<CartItemShare>>("UserCart");
            if (result == null)
            {
                result = new List<CartItemShare>();
            }
            return View(result);
        }

        public IActionResult Delete(int id)
        {
            List<CartItemShare> cart = HttpContext.Session.Get<List<CartItemShare>>("UserCart");

            var deleteMe = cart.Find(x => x.ProductId == id);

            cart.Remove(deleteMe);
            HttpContext.Session.Set("UserCart", cart);
            Task.WaitAll(Task.Delay(2000));
            return RedirectToAction("Index", "Cart");
        }

    }
}

CustomerSite/Controllers/HomeController.cs
using CustomerSite.Models;
using CustomerSite.SerVices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;

namespace CustomerSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductApiClient _productApiClient;

        public HomeController(ILogger<HomeController> logger,IProductApiClient productApiClient)
        {
            _logger = logger;
            _productApiClient = productApiClient;
        }

        public async Task<IActionResult> Index()
        {
             var results = await _productApiClient.GetProducts();
            return View(results);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CustomerSite/Controllers/ProductController.cs
using CustomerSite.SerVices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ShareModel;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CustomerSite.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;

        public ProductController(IProductApiClient productApiClient)
        {
            _productApiClient = productApiClient;
        }

        [Route("/Prodcut/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            var result = await _productApiClient.GetProductById(id);
            return View(result);
        }

        [Route("/Prodcut/category{categoryName}")]
        public async Task<IActionResult> CategoryById(string categoryName)
        {
            var results = await _productApiClient.GetProductByCategory(categoryName);
            return View(results);
        }

        public async Task<IActionResult> addProductToCart(int id, int qty)
        {
            List<CartItemShare> cart = HttpContext.Session.Get<List<CartItemShare>>("UserCart");
            if (cart == null)
            {
                cart = new List<CartItemShare>();
            }

            foreach (var item in cart)
            {
                if (item.ProductId == id)
                {
                    item.Quality += qty;
                    HttpContext.Session.Set<List<CartItemShare>>("UserCart", cart);
                    Task.WaitAll(Task.Delay(2000));
                    return RedirectToAction("Details", "Product", new { id = id });
                }
            }

            var product = await _productApiClient.GetProductById(id);
            var productItem = new CartItemShare
            {
                ProductId = (int)product.ProductID,
                ProductName = product.ProductName,
                Price = (decimal)product.Price,
                Quality = qty,
                Image = product.Image
            };

            cart.Add(productItem);
            HttpContext.Session.Set<List<CartItemShare>>("UserCart", cart);

            Task.WaitAll(Task.Delay(2000));
            return RedirectToAction("Details", "Product", new { id = id });
        }

    }
}

CustomerSite/Controllers/RatingController.cs
using CustomerSite.SerVices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CustomerSite.Controllers
{
    public class RatingController : Controller
    {
        private readonly IProductApiClient _productApiClient;

        public RatingController(IProductApiClient productApiClient)
        {
            _productApiClient = productApiClient;
        }

        [Authorize]
        public async Task<IActionResult> Voting(int ProductID, int rating)
        {
            string uri_redirect = Request.Headers["Referer"].ToString();
            var result = await _productApiClient.Rating(ProductID, rating);

            if (result is false)
            {
                return Content("false");
            }
            return Redirect(uri_redirect);
        }
    }
}

CustomerSite/ViewComponents/CategoryMenuViewComponent.cs
using CustomerSite.SerVices;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CustomerSite.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private readonly ICategoryApiClient _categoryApiClient;

        public CategoryMenuViewComponent (ICategoryApiClient categoryApiClient)
        {
            _categoryApiClient = categoryApiClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryApiClient.GetCategories();

            return View(categories);
        }

    }
}

CustomerSite/Views/Cart/Index.cshtml
@{
    ViewData["Title"] = "Cart Page";
}

@model List<ShareModel.CartItemShare>
@{ decimal sumPrice = 0;}
<div class="divider" style="text-align: center;"><span></span><span class="title-products" style="font-size:32px;color:crimson">Giỏ hàng</span><span></span></div>
<div>
    @foreach (var item in @Model)
    {
        <div class="container-fluid" style="margin-top:20px; margin-bottom:20px;">
            <div class="row">
                <div class="col-2">
                    <img src="@item.Image" alt="cartItemImage" style="width:150px" />
                </div>
                <div class="col">
                    <div class="row">
                        <label>Tên sản phẩm : </label>
                        <b style="margin-left:10px">@item.ProductName</b>
                    </div>
                    <div class="row">
                        <label> Giá tiền : </label>
                        <a style="margin-left:10px">@string.Concat(string.Format("{0:#,##0}", item.Price), " vnđ")</a>
                        @{sumPrice += item.Price * item.Quality;}
                        <label style="margin-left:100px">Số lượng: </label>
                        <a style="margin-left:10px">@item.Quality</a>
                    </div>
                    <div class="row" style="float:right">
                        <button type="button" onclick=" location.href = '@Url.Action("Delete", "Cart", new { id = item.ProductId})';" class="btn btn-outline-danger btn-lg">Xóa sản phẩm</button>
                    </div>
                </div>
            </div>
        </div>
    }
    }
    </div>

CustomerSite/Views/Home/Index.cshtml
@model IList<ShareModel.ProductShare>
@{
    ViewData["Title"] = "Home Page";
}
@foreach (var product in Model)
{
<div class="col-3" style="float:left;margin-top:20px">
    <div class="card m-lg-3" style="background-color:#E8E8E8">
        <div class="card-header" style="background-color: #696969; text-align: center; ">
            <h4 class="my-0 font-weight-normal" style="width:300px; height:60px;">
                <label style="font-size:23px;  text-shadow: black 4px 5px 6px;
    color: #FFCC66; text-align:center; ">@product.ProductName</label>
            </h4>
        </div>
        <img src="@product.Image" alt="New york" style="height:400px;">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <p style="font-size:20px; color:#a51313;"><b>Giá:@product.Price</b> VNĐ</p>
                </div>
            </div>
            <div style="text-align:center;">
                <a asp-action="Details" asp-controller="Product" class="btn btn-success" asp-route-id="@product.ProductID">Xem thêm</a>
            </div>
        </div>
    </div>
</div>
}

CustomerSite/Views/Product/CategoryById.cshtml
@model IList<ShareModel.ProductFromCategory>

@if (Model.Count() != 0)
{
    <div class="row">
        @foreach (var product in Model)
        {
            <div class="col-3" style="float:left;margin-top:20px">
                <div class="card m-lg-3" style="background-color:#E8E8E8">
                    <div class="card-header" style="background-color: #696969; text-align: center; ">
                        <h4 class="my-0 font-weight-normal" style="width:300px; height:60px;">
                            <label style="font-size:23px;text-shadow: black 4px 5px 6px; color: #FFCC66;">@product.ProductName</label>
                        </h4>
                    </div>

                    <img src="@product.Img" alt="New york" style="height:450px;">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <p style="font-size:20px; color:#a51313;"><b>Giá:@product.Price</b> VNĐ</p>
                            </div>                  
                        </div>
                    </div>
                </div>

            </div>

        }
    </div>
}
else
{
    <div class="row">
        <strong>Không có sản phẩm nào!</strong>
    </div>
}

CustomerSite/Views/Product/Default.cshtml
@model IList<ShareModel.ProductShare>

@foreach (var pro in Model)
{
    <div class="col-4" style="float:left">
        <div class="card mb-4">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal" style="width:213px; height:54px;">
                    <label style="font-size:23px;color:steelblue;">@pro.ProductName</label>
                </h4>
            </div>
            <img src="@pro.Image" alt="New york" style="height:450px;">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <p style="font-size:20px; color:#a51313;"><b>Giá:@pro.Price</b> VNĐ</p>
                    </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <p style="font-size:20px; color:#a51313;"><b>@pro.Description</b> </p>
                    </div>
                </div>
            </div>
        </div>
        </div>
                }

CustomerSite/Views/Product/Details.cshtml
@model ShareModel.ProductShare
@using Microsoft.AspNetCore.Http
        <div class="p-5 border rounded">
            <div class="form-group row ">
                <div class="col-6" style="width:100%; text-align: center;">
                    <img src="@Model.Image" alt="New york" style="height:450px;">
                </div>
                <div class="col-6">

                    <div class="product-name" style=" text-shadow: black 2px 3px 4px; color: #FFCC66;">
                        <h1>@Model.ProductName</h1>
                    </div>
                    <hr />
                    <p>
                        <span class="item-title">ID:</span>
                        <span>
                            <strong>
                                @Model.ProductID
                            </strong>
                        </span>
                    </p>
                    <p>
                        <span class="item-title">Description: @Model.Description</span>
                    </p>
                    <p>
                        <span class="item-title">Category Name: @Model.CategoryName</span>
                    </p>
                    <div class="price-box">
                        <h3>@Model.Price.ToString().Insert(3, ".") VNĐ</h3>
                    </div>
                    <div>
                        @using (Html.BeginForm("addProductToCart", "Product", FormMethod.Post))
                        {
                            <input type="hidden" id="id" name="id" value=@Model.ProductID />
                            <input type="hidden" id="qty" name="qty" value=1 />
                            <button id="addCart" name="addCart" type="submit" class="btn btn-primary btn-lg btn-block"><i class="fas fa-shopping-cart"></i> Thêm vào giỏ hàng</button>
                        }
                    </div>
                    <div class="form-group">
                        <input hidden asp-for="@Model.ProductID" />
                        <a asp-controller="Home" asp-action="Index" class="btn btn-success">Back</a>
                    </div>
                </div>
            </div>
        </div>


@if (User.Identity.IsAuthenticated)
{
    @using (Html.BeginForm("Voting", "Rating"))
        {
            @Html.HiddenFor(x => x.ProductID)
            <span class="rate-area">
                <h5 class="rate">Rate Product</h5>
                <input type="submit" id="5-star" name="rating" value="5" />
                <label for="5-star" title="Amazing">5 stars</label>

                <input type="submit" id="4-star" name="rating" value="4" />
                <label for="4-star" title="Good">4 stars</label>

                <input type="submit" id="3-star" name="rating" value="3" />
                <label for="3-star" title="Average">3 stars</label>

                <input type="submit" id="2-star" name="rating" value="2" />
                <label for="2-star" title="Not Good">2 stars</label>

                <input type="submit" id="1-star" name="rating" value="1" />
                <label for="1-star" title="Bad">1 star</label>
            </span>

        }
    
 }

CustomerSite/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IList<ShareModel.CategoryShare>

<ul class="nav-navbar-nav flex-grow-1">
    @foreach (var category in Model)
    {
    <li class="nav-item" style=" display: inline-block;float:left;font-size:15px">
        <a class="nav-link text-light" asp-controller="Product" asp-action="CategoryById" asp-route-categoryName="@category.CategoryName">@category.CategoryName</a>  
    </li>
    }
</ul>

CustomerSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustomerSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <nav class="navbar navbar-inverse navbar-fixed-top">
                        <ul class="navbar-nav flex-grow-1">
                            <li>
                                <a asp-area="" asp-controller="Home" asp-action="Index" itemprop="url">
                                    <img src="https://res.cloudinary.com/dusq8k6rj/image/upload/v1619406281/leduyen/logo_nylawv.png" alt="logo" style="width:100px; height:90px;" />
                                </a>
                            </li>
                            <li class="nav-item" , style="margin-top:15px;">
                                @await Component.InvokeAsync("CategoryMenu")
                            </li>
                            <li style="padding-top: 20px"><a href="~/cart" style="margin-left:750px"><i class="fas fa-shopping-cart" style="font-size:30px"></i></a></li>
                            <partial name="_LoginPartial" />

                        </ul>
                    </nav>
                </div>
            </div>
        </nav>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="https://res.cloudinary.com/dusq8k6rj/image/upload/v1619406281/leduyen/back1_jtpupi.jpg" alt="los angeles" style="width:100%; height:650px;">
                </div>

                <div class="item">
                    <img src="https://res.cloudinary.com/dusq8k6rj/image/upload/v1619406282/leduyen/back4_iiruiw.jpg" alt="chicago" style="width:100%;height:650px;">
                </div>

                <div class="item">
                    <img src="https://res.cloudinary.com/dusq8k6rj/image/upload/v1619406282/leduyen/back3_z5nksz.jpg" alt="new york" style="width:100%;height:650px;">
                </div>
                <div class="item">
                    <img src="https://res.cloudinary.com/dusq8k6rj/image/upload/v1619406282/leduyen/back2_lqflf3.jpg" alt="New york" style="width:100%;height:650px;">
                </div>

            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

    </header>
    <div class="row">

        <main role="main" class="pb-3" style="width:100%">
            @RenderBody()

        </main>
    </div>

    <!-- Site footer -->
    <footer class="site-footer" style="background-color: #000000; color:#ffffff">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <h4>About</h4>
                    <p class="text-justify">We trust that nobody ought to need to trade off their wellbeing for beauty. Together with our brands, we’re standing firm AGAINST TOXINS in close to home consideration, declining to make due with anything other than the most secure, best items. We’re moving the attitudes — and building a network of activists who need a superior sort of beauty.</p>
                </div>

                <div class="col-xs-6 col-md-3">
                    <h4>Categories</h4>
                    <ul class="footer-links">
                        <li><a href="/">LipStick</a></li>
                        <li><a href="/">SkinCare</a></li>
                        <li><a href="/">LipCare</a></li>
                       
                    </ul>
                </div>

                <div class="col-xs-6 col-md-3">
                    <h4>Quick Links</h4>
                    <ul class="footer-links">
                        <li><a href="/">About Us</a></li>
                        <li><a href="/">Contact Us</a></li>
                        <li><a href="/">Contribute</a></li>
                        <li><a href="/">Privacy Policy</a></li>
                        <li><a href="/">Sitemap</a></li>
                    </ul>
                </div>
            </div>
            <hr>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p class="copyright-text">
                        Copyright &copy; 2021 All Rights Reserved by
                        <a href="#">LeDuyen</a>.
                    </p>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                    <ul class="social-icons">
                        <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>